# -*- coding: utf-8 -*-
"""Trabalhando com conjuntos

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SDTP8MVUu46d3ZN5nttyhv-FI-VBG8jm
"""

usuarios_data_science = [15, 23, 43, 56]
usuarios_machine_learning = [13, 23, 56, 42]

assistiram = []
assistiram.extend(usuarios_data_science)
assistiram

assistiram = usuarios_data_science.copy()
assistiram

assistiram = usuarios_data_science.copy()
assistiram.extend(usuarios_machine_learning)
assistiram

len(assistiram)

set(assistiram)

set([1, 2, 3])

set([1, 2, 3, 1])

{4, 1, 3, 2}

type({1, 2})

usuarios_data_science = {15, 23, 43, 56}
usuarios_machine_learning = {13, 23, 56, 42}

usuarios_machine_learning[3]

for usuario in set(assistiram):
    print(usuario)

usuarios_data_science = {15, 23, 43, 56}
usuarios_machine_learning = {13, 23, 56, 42}

usuarios_data_science | usuarios_machine_learning  # ou

usuarios_data_science & usuarios_machine_learning  # e

# remove os que se repetem no outro conjunto
usuarios_data_science - usuarios_machine_learning

fez_ds_naofez_ml = usuarios_data_science - usuarios_machine_learning
15 in fez_ds_naofez_ml

23 in fez_ds_naofez_ml

usuarios_data_science ^ usuarios_machine_learning  # ou exclusivo

usuarios = {1, 5, 76, 34, 52, 13, 17}
len(usuarios)

usuarios.append(13)     # não aceita adicionar, porque não tem índice
len(usuarios)

usuarios.add(13)    # o 13 já está no conjunto
len(usuarios)

usuarios.add(75)
len(usuarios)

usuarios

usuarios = frozenset(usuarios)  # conjunto fechado
usuarios

type(usuarios)

usuarios.add(36)    # o frozenset não deixa adicionar elementos

meu_texto = "Bem vindo meu nome é Guilherme eu gosto muito de nomes e tenho o meu cachorro e gosto muito de cachorro"
meu_texto.split()   # quebra o texto da lista em pedaços

# quebra o texto e transforma em conjunto, então não repete palavras
set(meu_texto.split())
